class Solution:
    def alphabetBoardPath(self, target: str) -> str:
        output = ""
        board = ["abcde", "fghij", "klmno", "pqrst", "uvwxy", "z"]
        alpha_pos = {"a": (0, 0), "b": (0, 1), "c": (0, 2), "d": (0, 3), "e": (0, 4), "f": (1, 0), "g": (1, 1),
                     "h": (1, 2), "i": (1, 3), "j": (1, 4), "k": (2, 0), "l": (2, 1), "m": (2, 2), "n": (2, 3),
                     "o": (2, 4), "p": (3, 0), "q": (3, 1), "r": (3, 2), "s": (3, 3), "t": (3, 4), "u": (4, 0),
                     "v": (4, 1), "w": (4, 2), "x": (4, 3), "y": (4, 4), "z": (5, 0)}
        board_path = {"aa": "!", "ab": "R!", "ac": "RR!", "ad": "RRR!", "ae": "RRRR!", "af": "D!", "ag": "DR!",
                      "ah": "DRR!", "ai": "DRRR!", "aj": "DRRRR!", "ak": "DD!", "al": "DDR!", "am": "DDRR!",
                      "an": "DDRRR!", "ao": "DDRRRR!", "ap": "DDD!", "aq": "DDDR!", "ar": "DDDRR!", "as": "DDDRRR!",
                      "at": "DDDRRRR!", "au": "DDDD!", "av": "DDDDR!", "aw": "DDDDRR!", "ax": "DDDDRRR!",
                      "ay": "DDDDRRRR!", "az": "DDDDD!", "ba": "L!", "bb": "!", "bc": "R!", "bd": "RR!", "be": "RRR!",
                      "bf": "DL!", "bg": "D!", "bh": "DR!", "bi": "DRR!", "bj": "DRRR!", "bk": "DDL!", "bl": "DD!",
                      "bm": "DDR!", "bn": "DDRR!", "bo": "DDRRR!", "bp": "DDDL!", "bq": "DDD!", "br": "DDDR!",
                      "bs": "DDDRR!", "bt": "DDDRRR!", "bu": "DDDDL!", "bv": "DDDD!", "bw": "DDDDR!", "bx": "DDDDRR!",
                      "by": "DDDDRRR!", "bz": "DDDDLD!", "ca": "LL!", "cb": "L!", "cc": "!", "cd": "R!", "ce": "RR!",
                      "cf": "DLL!", "cg": "DL!", "ch": "D!", "ci": "DR!", "cj": "DRR!", "ck": "DDLL!", "cl": "DDL!",
                      "cm": "DD!", "cn": "DDR!", "co": "DDRR!", "cp": "DDDLL!", "cq": "DDDL!", "cr": "DDD!",
                      "cs": "DDDR!", "ct": "DDDRR!", "cu": "DDDDLL!", "cv": "DDDDL!", "cw": "DDDD!", "cx": "DDDDR!",
                      "cy": "DDDDRR!", "cz": "DDDDLLD!", "da": "LLL!", "db": "LL!", "dc": "L!", "dd": "!", "de": "R!",
                      "df": "DLLL!", "dg": "DLL!", "dh": "DL!", "di": "D!", "dj": "DR!", "dk": "DDLLL!", "dl": "DDLL!",
                      "dm": "DDL!", "dn": "DD!", "do": "DDR!", "dp": "DDDLLL!", "dq": "DDDLL!", "dr": "DDDL!",
                      "ds": "DDD!", "dt": "DDDR!", "du": "DDDDLLL!", "dv": "DDDDLL!", "dw": "DDDDL!", "dx": "DDDD!",
                      "dy": "DDDDR!", "dz": "DDDDLLLD!", "ea": "LLLL!", "eb": "LLL!", "ec": "LL!", "ed": "L!",
                      "ee": "!", "ef": "DLLLL!", "eg": "DLLL!", "eh": "DLL!", "ei": "DL!", "ej": "D!", "ek": "DDLLLL!",
                      "el": "DDLLL!", "em": "DDLL!", "en": "DDL!", "eo": "DD!", "ep": "DDDLLLL!", "eq": "DDDLLL!",
                      "er": "DDDLL!", "es": "DDDL!", "et": "DDD!", "eu": "DDDDLLLL!", "ev": "DDDDLLL!", "ew": "DDDDLL!",
                      "ex": "DDDDL!", "ey": "DDDD!", "ez": "DDDDLLLLD!", "fa": "U!", "fb": "UR!", "fc": "URR!",
                      "fd": "URRR!", "fe": "URRRR!", "ff": "!", "fg": "R!", "fh": "RR!", "fi": "RRR!", "fj": "RRRR!",
                      "fk": "D!", "fl": "DR!", "fm": "DRR!", "fn": "DRRR!", "fo": "DRRRR!", "fp": "DD!", "fq": "DDR!",
                      "fr": "DDRR!", "fs": "DDRRR!", "ft": "DDRRRR!", "fu": "DDD!", "fv": "DDDR!", "fw": "DDDRR!",
                      "fx": "DDDRRR!", "fy": "DDDRRRR!", "fz": "DDDD!", "ga": "UL!", "gb": "U!", "gc": "UR!",
                      "gd": "URR!", "ge": "URRR!", "gf": "L!", "gg": "!", "gh": "R!", "gi": "RR!", "gj": "RRR!",
                      "gk": "DL!", "gl": "D!", "gm": "DR!", "gn": "DRR!", "go": "DRRR!", "gp": "DDL!", "gq": "DD!",
                      "gr": "DDR!", "gs": "DDRR!", "gt": "DDRRR!", "gu": "DDDL!", "gv": "DDD!", "gw": "DDDR!",
                      "gx": "DDDRR!", "gy": "DDDRRR!", "gz": "DDDLD!", "ha": "ULL!", "hb": "UL!", "hc": "U!",
                      "hd": "UR!", "he": "URR!", "hf": "LL!", "hg": "L!", "hh": "!", "hi": "R!", "hj": "RR!",
                      "hk": "DLL!", "hl": "DL!", "hm": "D!", "hn": "DR!", "ho": "DRR!", "hp": "DDLL!", "hq": "DDL!",
                      "hr": "DD!", "hs": "DDR!", "ht": "DDRR!", "hu": "DDDLL!", "hv": "DDDL!", "hw": "DDD!",
                      "hx": "DDDR!", "hy": "DDDRR!", "hz": "DDDLLD!", "ia": "ULLL!", "ib": "ULL!", "ic": "UL!",
                      "id": "U!", "ie": "UR!", "if": "LLL!", "ig": "LL!", "ih": "L!", "ii": "!", "ij": "R!",
                      "ik": "DLLL!", "il": "DLL!", "im": "DL!", "in": "D!", "io": "DR!", "ip": "DDLLL!", "iq": "DDLL!",
                      "ir": "DDL!", "is": "DD!", "it": "DDR!", "iu": "DDDLLL!", "iv": "DDDLL!", "iw": "DDDL!",
                      "ix": "DDD!", "iy": "DDDR!", "iz": "DDDLLLD!", "ja": "ULLLL!", "jb": "ULLL!", "jc": "ULL!",
                      "jd": "UL!", "je": "U!", "jf": "LLLL!", "jg": "LLL!", "jh": "LL!", "ji": "L!", "jj": "!",
                      "jk": "DLLLL!", "jl": "DLLL!", "jm": "DLL!", "jn": "DL!", "jo": "D!", "jp": "DDLLLL!",
                      "jq": "DDLLL!", "jr": "DDLL!", "js": "DDL!", "jt": "DD!", "ju": "DDDLLLL!", "jv": "DDDLLL!",
                      "jw": "DDDLL!", "jx": "DDDL!", "jy": "DDD!", "jz": "DDDLLLLD!", "ka": "UU!", "kb": "UUR!",
                      "kc": "UURR!", "kd": "UURRR!", "ke": "UURRRR!", "kf": "U!", "kg": "UR!", "kh": "URR!",
                      "ki": "URRR!", "kj": "URRRR!", "kk": "!", "kl": "R!", "km": "RR!", "kn": "RRR!", "ko": "RRRR!",
                      "kp": "D!", "kq": "DR!", "kr": "DRR!", "ks": "DRRR!", "kt": "DRRRR!", "ku": "DD!", "kv": "DDR!",
                      "kw": "DDRR!", "kx": "DDRRR!", "ky": "DDRRRR!", "kz": "DDD!", "la": "UUL!", "lb": "UU!",
                      "lc": "UUR!", "ld": "UURR!", "le": "UURRR!", "lf": "UL!", "lg": "U!", "lh": "UR!", "li": "URR!",
                      "lj": "URRR!", "lk": "L!", "ll": "!", "lm": "R!", "ln": "RR!", "lo": "RRR!", "lp": "DL!",
                      "lq": "D!", "lr": "DR!", "ls": "DRR!", "lt": "DRRR!", "lu": "DDL!", "lv": "DD!", "lw": "DDR!",
                      "lx": "DDRR!", "ly": "DDRRR!", "lz": "DDLD!", "ma": "UULL!", "mb": "UUL!", "mc": "UU!",
                      "md": "UUR!", "me": "UURR!", "mf": "ULL!", "mg": "UL!", "mh": "U!", "mi": "UR!", "mj": "URR!",
                      "mk": "LL!", "ml": "L!", "mm": "!", "mn": "R!", "mo": "RR!", "mp": "DLL!", "mq": "DL!",
                      "mr": "D!", "ms": "DR!", "mt": "DRR!", "mu": "DDLL!", "mv": "DDL!", "mw": "DD!", "mx": "DDR!",
                      "my": "DDRR!", "mz": "DDLLD!", "na": "UULLL!", "nb": "UULL!", "nc": "UUL!", "nd": "UU!",
                      "ne": "UUR!", "nf": "ULLL!", "ng": "ULL!", "nh": "UL!", "ni": "U!", "nj": "UR!", "nk": "LLL!",
                      "nl": "LL!", "nm": "L!", "nn": "!", "no": "R!", "np": "DLLL!", "nq": "DLL!", "nr": "DL!",
                      "ns": "D!", "nt": "DR!", "nu": "DDLLL!", "nv": "DDLL!", "nw": "DDL!", "nx": "DD!", "ny": "DDR!",
                      "nz": "DDLLLD!", "oa": "UULLLL!", "ob": "UULLL!", "oc": "UULL!", "od": "UUL!", "oe": "UU!",
                      "of": "ULLLL!", "og": "ULLL!", "oh": "ULL!", "oi": "UL!", "oj": "U!", "ok": "LLLL!", "ol": "LLL!",
                      "om": "LL!", "on": "L!", "oo": "!", "op": "DLLLL!", "oq": "DLLL!", "or": "DLL!", "os": "DL!",
                      "ot": "D!", "ou": "DDLLLL!", "ov": "DDLLL!", "ow": "DDLL!", "ox": "DDL!", "oy": "DD!",
                      "oz": "DDLLLLD!", "pa": "UUU!", "pb": "UUUR!", "pc": "UUURR!", "pd": "UUURRR!", "pe": "UUURRRR!",
                      "pf": "UU!", "pg": "UUR!", "ph": "UURR!", "pi": "UURRR!", "pj": "UURRRR!", "pk": "U!",
                      "pl": "UR!", "pm": "URR!", "pn": "URRR!", "po": "URRRR!", "pp": "!", "pq": "R!", "pr": "RR!",
                      "ps": "RRR!", "pt": "RRRR!", "pu": "D!", "pv": "DR!", "pw": "DRR!", "px": "DRRR!", "py": "DRRRR!",
                      "pz": "DD!", "qa": "UUUL!", "qb": "UUU!", "qc": "UUUR!", "qd": "UUURR!", "qe": "UUURRR!",
                      "qf": "UUL!", "qg": "UU!", "qh": "UUR!", "qi": "UURR!", "qj": "UURRR!", "qk": "UL!", "ql": "U!",
                      "qm": "UR!", "qn": "URR!", "qo": "URRR!", "qp": "L!", "qq": "!", "qr": "R!", "qs": "RR!",
                      "qt": "RRR!", "qu": "DL!", "qv": "D!", "qw": "DR!", "qx": "DRR!", "qy": "DRRR!", "qz": "DLD!",
                      "ra": "UUULL!", "rb": "UUUL!", "rc": "UUU!", "rd": "UUUR!", "re": "UUURR!", "rf": "UULL!",
                      "rg": "UUL!", "rh": "UU!", "ri": "UUR!", "rj": "UURR!", "rk": "ULL!", "rl": "UL!", "rm": "U!",
                      "rn": "UR!", "ro": "URR!", "rp": "LL!", "rq": "L!", "rr": "!", "rs": "R!", "rt": "RR!",
                      "ru": "DLL!", "rv": "DL!", "rw": "D!", "rx": "DR!", "ry": "DRR!", "rz": "DLLD!", "sa": "UUULLL!",
                      "sb": "UUULL!", "sc": "UUUL!", "sd": "UUU!", "se": "UUUR!", "sf": "UULLL!", "sg": "UULL!",
                      "sh": "UUL!", "si": "UU!", "sj": "UUR!", "sk": "ULLL!", "sl": "ULL!", "sm": "UL!", "sn": "U!",
                      "so": "UR!", "sp": "LLL!", "sq": "LL!", "sr": "L!", "ss": "!", "st": "R!", "su": "DLLL!",
                      "sv": "DLL!", "sw": "DL!", "sx": "D!", "sy": "DR!", "sz": "DLLLD!", "ta": "UUULLLL!",
                      "tb": "UUULLL!", "tc": "UUULL!", "td": "UUUL!", "te": "UUU!", "tf": "UULLLL!", "tg": "UULLL!",
                      "th": "UULL!", "ti": "UUL!", "tj": "UU!", "tk": "ULLLL!", "tl": "ULLL!", "tm": "ULL!",
                      "tn": "UL!", "to": "U!", "tp": "LLLL!", "tq": "LLL!", "tr": "LL!", "ts": "L!", "tt": "!",
                      "tu": "DLLLL!", "tv": "DLLL!", "tw": "DLL!", "tx": "DL!", "ty": "D!", "tz": "DLLLLD!",
                      "ua": "UUUU!", "ub": "UUUUR!", "uc": "UUUURR!", "ud": "UUUURRR!", "ue": "UUUURRRR!", "uf": "UUU!",
                      "ug": "UUUR!", "uh": "UUURR!", "ui": "UUURRR!", "uj": "UUURRRR!", "uk": "UU!", "ul": "UUR!",
                      "um": "UURR!", "un": "UURRR!", "uo": "UURRRR!", "up": "U!", "uq": "UR!", "ur": "URR!",
                      "us": "URRR!", "ut": "URRRR!", "uu": "!", "uv": "R!", "uw": "RR!", "ux": "RRR!", "uy": "RRRR!",
                      "uz": "D!", "va": "UUUUL!", "vb": "UUUU!", "vc": "UUUUR!", "vd": "UUUURR!", "ve": "UUUURRR!",
                      "vf": "UUUL!", "vg": "UUU!", "vh": "UUUR!", "vi": "UUURR!", "vj": "UUURRR!", "vk": "UUL!",
                      "vl": "UU!", "vm": "UUR!", "vn": "UURR!", "vo": "UURRR!", "vp": "UL!", "vq": "U!", "vr": "UR!",
                      "vs": "URR!", "vt": "URRR!", "vu": "L!", "vv": "!", "vw": "R!", "vx": "RR!", "vy": "RRR!",
                      "vz": "LD!", "wa": "UUUULL!", "wb": "UUUUL!", "wc": "UUUU!", "wd": "UUUUR!", "we": "UUUURR!",
                      "wf": "UUULL!", "wg": "UUUL!", "wh": "UUU!", "wi": "UUUR!", "wj": "UUURR!", "wk": "UULL!",
                      "wl": "UUL!", "wm": "UU!", "wn": "UUR!", "wo": "UURR!", "wp": "ULL!", "wq": "UL!", "wr": "U!",
                      "ws": "UR!", "wt": "URR!", "wu": "LL!", "wv": "L!", "ww": "!", "wx": "R!", "wy": "RR!",
                      "wz": "LLD!", "xa": "UUUULLL!", "xb": "UUUULL!", "xc": "UUUUL!", "xd": "UUUU!", "xe": "UUUUR!",
                      "xf": "UUULLL!", "xg": "UUULL!", "xh": "UUUL!", "xi": "UUU!", "xj": "UUUR!", "xk": "UULLL!",
                      "xl": "UULL!", "xm": "UUL!", "xn": "UU!", "xo": "UUR!", "xp": "ULLL!", "xq": "ULL!", "xr": "UL!",
                      "xs": "U!", "xt": "UR!", "xu": "LLL!", "xv": "LL!", "xw": "L!", "xx": "!", "xy": "R!",
                      "xz": "LLLD!", "ya": "UUUULLLL!", "yb": "UUUULLL!", "yc": "UUUULL!", "yd": "UUUUL!",
                      "ye": "UUUU!", "yf": "UUULLLL!", "yg": "UUULLL!", "yh": "UUULL!", "yi": "UUUL!", "yj": "UUU!",
                      "yk": "UULLLL!", "yl": "UULLL!", "ym": "UULL!", "yn": "UUL!", "yo": "UU!", "yp": "ULLLL!",
                      "yq": "ULLL!", "yr": "ULL!", "ys": "UL!", "yt": "U!", "yu": "LLLL!", "yv": "LLL!", "yw": "LL!",
                      "yx": "L!", "yy": "!", "yz": "LLLLD!", "za": "UUUUU!", "zb": "UUUUUR!", "zc": "UUUUURR!",
                      "zd": "UUUUURRR!", "ze": "UUUUURRRR!", "zf": "UUUU!", "zg": "UUUUR!", "zh": "UUUURR!",
                      "zi": "UUUURRR!", "zj": "UUUURRRR!", "zk": "UUU!", "zl": "UUUR!", "zm": "UUURR!", "zn": "UUURRR!",
                      "zo": "UUURRRR!", "zp": "UU!", "zq": "UUR!", "zr": "UURR!", "zs": "UURRR!", "zt": "UURRRR!",
                      "zu": "U!", "zv": "UR!", "zw": "URR!", "zx": "URRR!", "zy": "URRRR!", "zz": "!"}
        s = "a"
        for t in target:
            output += board_path[s + t]
            s = t
        return output
